travis:
  secure:
    BINSTAR_TOKEN: K+vXcR0iwtc9IgU2Wlin9owWQqNTSBU2B0lHMSQbH1lovkmsPFE2YnhVIpXQPc24z+MomEY+Hkoda5+/9JubwYLuhGNrP3kqIznJpBK9p+0r3oFQuYR++NY7nacHYpkyAZIbH+DptxsZPJFHqccsveGbLp0G52EjEOSDwMAmFTCyNIUzL5BHHBOtcycVupqgTd3zJc0M56fCULxTiLidwrKCD3Gj+ujF/d+DtGqfkxEr4XtnD6jdgGCfmLh/c0Bu/3EgfxKOHNTA15IOlkqYgjoUqur8nKtHmrfGu8HcYz/fICY11mFWJKvcai3nZMnKtP5ihKWKWKPuUXnQyRLO9d6rVBBpziG93coLMpw3VqI4AySDltddicfP51q9t8U+QoAAr7+yEzKXcy/F9Bywqpa3sIV+dAggI6d78xAtQcydZUgOYpUSkhavPnPMXEgTlk9Hws+JJ29W8dWkc55z1GOORAPBv4dVdjyazkNd9lH2fX6iHiD7/5nePhvsXlR/3yBPqyV3Qt5azOqd39BdnBRkgV+FSJg5YcmUrzTkxyuTnSHyLG1tKD4IYJaazM64pNZI4Kz5Hd2wJwNDkBWp5gHdHGIAlh9ysaFQ6qSF92Q+2SBzisoQ34zgLZsfcKMtiifuQBQzJDpYb90xqlYcKsXvdr9BWIue+XqaSQXt9UA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
